/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.pjgg.sparkStreamming.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WordsCount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WordsCount\",\"namespace\":\"org.pjgg.sparkStreamming.avro\",\"fields\":[{\"name\":\"aggr\",\"type\":{\"type\":\"map\",\"values\":\"int\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Integer> aggr;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public WordsCount() {}

  /**
   * All-args constructor.
   */
  public WordsCount(java.util.Map<java.lang.CharSequence,java.lang.Integer> aggr) {
    this.aggr = aggr;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return aggr;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: aggr = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'aggr' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> getAggr() {
    return aggr;
  }

  /**
   * Sets the value of the 'aggr' field.
   * @param value the value to set.
   */
  public void setAggr(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
    this.aggr = value;
  }

  /** Creates a new WordsCount RecordBuilder */
  public static org.pjgg.sparkStreamming.avro.WordsCount.Builder newBuilder() {
    return new org.pjgg.sparkStreamming.avro.WordsCount.Builder();
  }
  
  /** Creates a new WordsCount RecordBuilder by copying an existing Builder */
  public static org.pjgg.sparkStreamming.avro.WordsCount.Builder newBuilder(org.pjgg.sparkStreamming.avro.WordsCount.Builder other) {
    return new org.pjgg.sparkStreamming.avro.WordsCount.Builder(other);
  }
  
  /** Creates a new WordsCount RecordBuilder by copying an existing WordsCount instance */
  public static org.pjgg.sparkStreamming.avro.WordsCount.Builder newBuilder(org.pjgg.sparkStreamming.avro.WordsCount other) {
    return new org.pjgg.sparkStreamming.avro.WordsCount.Builder(other);
  }
  
  /**
   * RecordBuilder for WordsCount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WordsCount>
    implements org.apache.avro.data.RecordBuilder<WordsCount> {

    private java.util.Map<java.lang.CharSequence,java.lang.Integer> aggr;

    /** Creates a new Builder */
    private Builder() {
      super(org.pjgg.sparkStreamming.avro.WordsCount.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.pjgg.sparkStreamming.avro.WordsCount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.aggr)) {
        this.aggr = data().deepCopy(fields()[0].schema(), other.aggr);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing WordsCount instance */
    private Builder(org.pjgg.sparkStreamming.avro.WordsCount other) {
            super(org.pjgg.sparkStreamming.avro.WordsCount.SCHEMA$);
      if (isValidValue(fields()[0], other.aggr)) {
        this.aggr = data().deepCopy(fields()[0].schema(), other.aggr);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'aggr' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Integer> getAggr() {
      return aggr;
    }
    
    /** Sets the value of the 'aggr' field */
    public org.pjgg.sparkStreamming.avro.WordsCount.Builder setAggr(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
      validate(fields()[0], value);
      this.aggr = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'aggr' field has been set */
    public boolean hasAggr() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'aggr' field */
    public org.pjgg.sparkStreamming.avro.WordsCount.Builder clearAggr() {
      aggr = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public WordsCount build() {
      try {
        WordsCount record = new WordsCount();
        record.aggr = fieldSetFlags()[0] ? this.aggr : (java.util.Map<java.lang.CharSequence,java.lang.Integer>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
